name: "carl_PS_var"
platform: "onnxruntime"
max_batch_size: 256
input [
 {
    name: "Electron_set"
    data_type: TYPE_FP32
    dims: [ 1, 4, -1 ]
 }
]
input [
 {
    name: "Jet_set"
    data_type: TYPE_FP32
    dims: [ 1, 5, -1 ]
 }
]
input [
 {
    name: "sample_indices"
    data_type: TYPE_INT64
    dims: [ 2, -1 ]
 }
]
output [
 {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, 1 ]
 }
]
instance_group [{ kind: KIND_GPU }]
version_policy: { all { }}
dynamic_batching { }
